### ISSUE TITLE
TypeError: NugetVersion unhashable type: 'Version'

### ISSUE THREAD

**Issue by ziadhany** [nexB/univers#128]
```
>>> set([NugetVersion(string='7.0.11')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<attrs generated hash univers.versions.Version>", line 2, in __hash__
TypeError: unhashable type: 'Version'

```

**Comment by ziadhany** [comment]
We should update univers version in [nexb/vulnerablecode](https://github.com/nexB/vulnerablecode/blob/main/requirements.txt#L109) to be >=30.10.1 .
Not related to univers
